language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - cache

before_deploy:
  - "yarn build"

deploy:
  provider: surge
  project: ./public/
  domain: vmello.com
  skip_cleanup: true
