name: vmello-website-ci

on: [push]

jobs:
  lint-build-test:
    name: Lint / Build / Test
    runs-on: ubuntu-22.04 # avoid latest for now: https://github.com/puppeteer/puppeteer/issues/12818
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Test Resume Export
        run: yarn resume:generate
